### ISSUE TITLE
Reciprocal of mode seeking loss 

### ISSUE THREAD

**Issue by Pikauba** [HelenMao/MSGAN#17]
You seem to use the reciprocal of your mode seeking loss at [line 131](https://github.com/HelenMao/MSGAN/blob/master/Pix2Pix-Mode-Seeking/models/pix2pix_model.py#L131) instead of minimizing the inverse of the function to maximize it. Nowhere in your paper you state doing so. Is there a particular reason for this because optimizing the reciprocal is not the same as optimizing the inverse of a function.

**Comment by Pikauba** [comment]
This seems to have been already discussed in a [different thread](https://github.com/HelenMao/MSGAN/issues/2) sorry for the duplicate. However, you state that minimizing the reciprocal is the same as minimizing the inverse of the function while this is just mathematically false. I would like to know why you chose this over the inverse function.

**Comment by HelenMao** [comment]
Hi, thanks for your interest in our work.
The tendency is similar. Our implementation is different from the one that directly inverses the function.
You can derive the gradient concerning the output image I1 and will find minimizing the reciprocal of the regularization  can be derived as 
![image](https://user-images.githubusercontent.com/17196207/96219310-6102e980-0f3b-11eb-895e-ff2905732901.png)
The ratio is just d(I1,I2)/d(z1,z2)
We can then find the gradient automatically adjusted when the mode-collapse problem is mitigated during the optimization. Namely, when the mode-collapse problem is reducing, the ratio and d(I1,I2) are becoming large, the gradient is becoming smaller too.
However, for the inverse one, 
![image](https://user-images.githubusercontent.com/17196207/96219427-ab846600-0f3b-11eb-8d39-5b9c0ee5d5fa.png)
d(z1,z2) is fixed.
[DSGAN](https://arxiv.org/abs/1901.09024), which is the concurrent work, adopts the inverse implementation. And we also find the lambda of DSGAN is always larger than ours. lamda_ds always be 4-10, while lambda_ms always be 0.5-1.25.
Also, in this version's implementation, we directly average all the dimensions instead of using a batch-wise mean. It is more reasonable to use a batch-wise mean. Although we find these two implementations have comparable results, we will update it in the future.
